baseurl: /
title: Anne's Website
theme: hugo-book
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
permalinks:
  post: /:year/:month/:day/:slug/
menu:
  main:
    - name: About
      url: /about/
    - name: GitHub
      url: https://github.com/AnneOkk
    - name: Twitter
      url: https://twitter.com/rstudio

markup:
  goldmark:
    renderer:
      unsafe: true
