---
title: R Markdown Workshop - Slides 
author: Anne Kleine
date: '2022-05-19'
slug: done
categories:
  - R Markdown Workshop
  - Day 1
tags:
  - r markdown 
  - workshop 
  - material
comments: no
# description: ''
removeBlur: no
images:
  - src: img/main/dayone.png
    alt: Desert Scene
    stretch: stretchH
weight: 1
---

## Day 1

### Get the slide decks! 

Get the slide deck for Day 1 here (PLEASE WAIT PATIENTLY!)

<iframe src="https://giphy.com/embed/wpvnJFDdXsBmdvLxjG" width="480" height="400" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/theoffice-episode-1-the-office-tv-wpvnJFDdXsBmdvLxjG"></a></p>


```{r echo = FALSE, include = FALSE}
knitr::include_url('https://anneokk.netlify.app/slides/day_one.html#1') 
```


Get the slide deck for Day 2 here (Wait PATIENTLY AGAIN)

```{r echo = FALSE, include = FALSE}
knitr::include_url('https://anneokk.netlify.app/slides/day_two.html#1') 
```


<iframe src="https://giphy.com/embed/Gj2iZfSI1rMmQ" width="480" height="470" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/Gj2iZfSI1rMmQ"></a></p>

